### ISSUE TITLE
一些可能的错字

### ISSUE THREAD

**Issue by jinde1573** [JJYing/General-Magic-Chinese-Subtitle#4]
200
00:15:39,500 --> 00:15:41,917
他不能告诉我到底进去之后做什么，「大」我当时就在想
他不能告诉我到底进去之后做什么，但我当时就在想

325
00:23:36,080 --> 00:23:39,120
最严重的是这个触摸屏非常「得」吵
最严重的是这个触摸屏非常的吵

332
00:24:00,290 --> 00:24:03,830
可以尽管天马行空地去发挥创意，团队有能力把「他」实现出来
可以尽管天马行空地去发挥创意，团队有能力把它实现出来

335
00:24:11,830 --> 00:24:14,290
像真的用户一样把「他」给使用起来
像真的用户一样把它给使用起来

348
00:24:53,450 --> 00:24:57,200
<font color="#ffffff"><b>Tony: </b></font>希望它能无缝「的」连接上，速度再快点
<font color="#ffffff"><b>Tony: </b></font>希望它能无缝地连接上，速度再快点

456
00:31:18,120 --> 00:31:22,540
闻起来像一只臭臭的羊，还穿了一件夏威夷风的「体」恤
闻起来像一只臭臭的羊，还穿了一件夏威夷风的T恤

529
00:36:48,040 --> 00:36:51,700
引领个人通讯进入一个崭新时代「时代」
引领个人通讯进入一个崭新时代

533
00:37:01,750 --> 00:37:04,870
这意味着我们不能再私底下偷偷摸摸、按部就班「的」做东西了
这意味着我们不能再私底下偷偷摸摸、按部就班地做东西了

562
00:38:48,370 --> 00:38:52,120
「他」会很实用，见到「他」的第一眼，我就会开心地笑
它会很实用，见到它的第一眼，我就会开心地笑

564
00:38:55,580 --> 00:38:59,290
我记得听他演讲的时候，脑中就不「对」附和「对！对！」
我记得听他演讲的时候，脑中就不断附和「对！对！」

590
00:40:22,790 --> 00:40:26,000
但是「他」真的会完全实现你们发布会上说的功能吗？」
但是它真的会完全实现你们发布会上说的功能吗？」

596
00:40:43,620 --> 00:40:45,830
也就是说没人说得「请」什么时候能买到？
也就是说没人说得清什么时候能买到？

642
00:43:17,000 --> 00:43:20,830
然后我说：「可以的，你脱脱看」，然后他就真「地」脱了……
然后我说：「可以的，你脱脱看」，然后他就真的脱了……

664
00:45:03,040 --> 00:45:06,080
不能点这里，点这「么」没用的，应该点那里」
（不过这句感觉像上海话？）
不能点这里，点这里没用的，应该点那里」

666
00:45:09,080 --> 00:45:12,080
[被测试者] 底下这个东西看起来有点像把「数字」
[被测试者] 底下这个东西看起来有点像把梳子

667
00:45:12,080 --> 00:45:15,910
我完全猜不出「他」代表什么意思
我完全猜不出它代表什么意思

675
00:45:30,950 --> 00:45:33,540
然后你就只能特码的看着「他」
然后你就只能特码的看着它

676
00:45:33,540 --> 00:45:36,250
然后你就只能「把」电源和电池，重启设备
然后你就只能拔电源和电池，重启设备

684
00:46:12,620 --> 00:46:16,120
我们的路演团队不得不每次都现场设置很大的屏幕和摄像机
我们的路演团队不得不每次都在现场设置很大的屏幕和摄像机

686
00:46:18,700 --> 00:46:24,580
我们设想中的设备你可以一直握在手中，「他」功能很多
我们设想中的设备你可以一直握在手中，它功能很多

733
00:49:28,870 --> 00:49:34,330
鼠标点击或者按键盘「他」才会有反应，浏览网页基本就是个被动的方式
鼠标点击或者按键盘它才会有反应，浏览网页基本就是个被动的方式

734
00:49:34,330 --> 00:49:37,620
<font color="#ffffff"><b>Stern: </b></font>尽管「着」一切就在我们眼皮底下发生
<font color="#ffffff"><b>Stern: </b></font>尽管这一切就在我们眼皮底下发生

736
00:49:55,660 --> 00:50:00,410
<font color="#ffffff"><b>MacAskill: </b></font>公司里有一个开发者，Pierre Omidyar，他平时超级安静，连说话都「吸」声细语
<font color="#ffffff"><b>MacAskill: </b></font>公司里有一个开发者，Pierre Omidyar，他平时超级安静，连说话都细声细语

772
00:52:03,120 --> 00:52:06,790
我们已经做「了」很不错了啊！还想咋样啊？
我们已经做得很不错了啊！还想咋样啊？

779
00:52:25,500 --> 00:52:28,120
当你提起「他们」的时候，都会有不同的反馈动作
当你提起它们的时候，都会有不同的反馈动作

780
00:52:28,120 --> 00:52:31,870
提这只猫的时候，它会抗拒
When I pick the cat up, it kind of scrunches up against （这句原文删掉）

809
00:54:09,410 --> 00:54:13,250
那就是整「体」做好玩的、有意思的部分
那就是整天做好玩的、有意思的部分

883
00:59:16,700 --> 00:59:18,870
只「须」轻轻一按
只需轻轻一按

926
01:02:19,450 --> 01:02:23,910
我意识到这根本「算不」是一门生意了，我们失败了
我意识到这根本不算是一门生意了，我们失败了

938
01:03:04,910 --> 01:03:10,160
不过「着」一切都取决于资源、优先级以及市场接受度
不过这一切都取决于资源、优先级以及市场接受度

968
01:04:38,000 --> 01:04:40,000
- 直接告诉我们「那」些可以播，哪些不能，就很好
- 确实，确实
- 直接告诉我们哪些可以播，哪些不能，就很好
- 确实，确实

1003
01:07:22,200 --> 01:07:28,750
才「换」过劲儿来，寻找新的方向
才缓过劲儿来，寻找新的方向

1074
01:13:37,200 --> 01:13:39,450
没法给大家、也没法给我自己一个交「待」
没法给大家、也没法给我自己一个交代

1092
01:15:29,790 --> 01:15:33,250
General Magic 就是其中这一波浪，「他」就存在于时间的一个小角落里
General Magic 就是其中这一波浪，它就存在于时间的一个小角落里

1109
01:16:49,950 --> 01:16:53,620
没有「着」一切的经历和成长
没有这一切的经历和成长

1114
01:17:24,160 --> 01:17:29,040
<font color="#ffffff"><b>Dee: </b></font> Tony 超级喜欢音乐，整「体」聊个不停
<font color="#ffffff"><b>Dee: </b></font> Tony 超级喜欢音乐，整天聊个不停

1116
01:17:33,000 --> 01:17:39,700
让我们可以把自己音乐都装进去，我不以为然：「我们为什么需要这玩意儿？」
让我们可以把自己的音乐都装进去，我不以为然：「我们为什么需要这玩意儿？」

1134
01:18:35,910 --> 01:18:38,290
给它加上了可以「按照」 App 的功能
给它加上了可以安装 App 的功能

1148
01:19:34,250 --> 01:19:37,910
用我们「着」十根手指
用我们这十根手指

1186
01:21:57,080 --> 01:21:59,450
你可以做个思想实验，「加入」 General Magic 从未诞生
你可以做个思想实验，假如 General Magic 从未诞生

1206
01:23:12,160 --> 01:23:14,160
<font color="#cccccc">[ LinkedIn 联合创始人 / CTO ]<br></font>所有这些公司「架」起来，我肯定算不出「了」其中的价值了
<font color="#cccccc">[ LinkedIn 联合创始人 / CTO ]<br></font>所有这些公司加起来，我肯定算不出来其中的价值了

1239
01:24:59,290 --> 01:25:02,080
尽可能「的」利用和释放天才们的才能
尽可能地利用和释放天才们的才能

**Comment by JJYing** [comment]
非常感谢细心指出~ 我去修正一下~
